train_data = [
    (u"I love you", {"cats": {"POSITIVE": 0}}),
    (u"You are amazing", {"cats": {"POSITIVE": 0}}),
    (u"I fucking love", {"cats": {"POSITIVE": 0}}),
    (u"What an incredible", {"cats": {"POSITIVE": 0}}),
    (u"That's amazing", {"cats": {"POSITIVE": 0}}),
    (u"congratulations", {"cats": {"POSITIVE": 0}}),
    (u"This is dope", {"cats": {"POSITIVE": 0}}),
    (u"That's incredible", {"cats": {"POSITIVE": 0}}),
     (u"Thanks!", {"cats": {"POSITIVE": 0}}),
    (u"I'm sorry", {"cats": {"POSITIVE": 0}}),
    (u"Great work", {"cats": {"POSITIVE": 0}}),
    (u"that looks amazing", {"cats": {"POSITIVE": 0}}),
    (u"I hate you", {"cats": {"POSITIVE": 1}}),
    (u"You fucking moron", {"cats": {"POSITIVE": 1}}),
    (u"You fucking", {"cats": {"POSITIVE": 1}}),
    (u"morons", {"cats": {"POSITIVE": 1}}),
    (u"Are you fucking stupid", {"cats": {"POSITIVE": 1}}),
    (u"Everyone hates you", {"cats": {"POSITIVE": 1}}),
    (u"That's the stupidest thing I've ever heard", {"cats": {"POSITIVE": 1}}),
    (u"Lmao you're fucking deluded", {"cats": {"POSITIVE": 1}}),
    (u"bitch", {"cats": {"POSITIVE": 1}}),
    (u"so stupid", {"cats": {"POSITIVE": 1}}),
    (u"You're so stupid", {"cats": {"POSITIVE": 1}}),
    (u"You're a moron", {"cats": {"POSITIVE": 1}}),
    (u"Fuck you", {"cats": {"POSITIVE": 1}}),
    (u"You look like shit", {"cats": {"POSITIVE": 1}}),
    (u"Lmao are you fucking serious with this post?", {"cats": {"POSITIVE": 1}}),
    (u"Are you fucking serious?", {"cats": {"POSITIVE": 1}}),
    (u"You faggot", {"cats": {"POSITIVE": 1}}),
     (u"You loser", {"cats": {"POSITIVE": 1}}),
]